### ISSUE TITLE
No real issue, just a question

### ISSUE THREAD

**Issue by blackhatma** [codUPLOADER/iw8offline#1]
Any plans on uploading the source of the CW dll? :) thanks for all your work man, super great stuff.

**Comment by codUPLOADER** [comment]
Yes
________________________________
From: yaboimikey97 ***@***.***>
Sent: Sunday, September 3, 2023 12:58 AM
To: codUPLOADER/iw8offline ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [codUPLOADER/iw8offline] No real issue, just a question (Issue #1)


Any plans on uploading the source of the CW dll? :) thanks for all your work man, super great stuff.

**Comment by nekodevelopers** [comment]
great job
